### ISSUE TITLE
Attempting to run after building in Ubuntu

### ISSUE THREAD

**Issue by jpruiz114** [Komorebi-Fork/komorebi#101]
Hello,

I followed the instructions of the readme file and they worked fine until I attempted to run the tool and got this:

```
Traceback (most recent call last):
  File "/usr/local/bin/komorebi", line 31, in <module>
    from komorebi.screen import Screen
ModuleNotFoundError: No module named 'komorebi'
```

I can't figure out what's wrong here.

I see the app installed in the applications list as well.

Thanks in advance.

**Comment by MonsterITServices** [comment]
Same. any help would be awesome.

**Comment by EDLLT** [comment]
> Hello,
> 
> I followed the instructions of the readme file and they worked fine until I attempted to run the tool and got this:
> 
> ```
> Traceback (most recent call last):
>   File "/usr/local/bin/komorebi", line 31, in <module>
>     from komorebi.screen import Screen
> ModuleNotFoundError: No module named 'komorebi'
> ```
> 
> I can't figure out what's wrong here.
> 
> I see the app installed in the applications list as well.
> 
> Thanks in advance.

Same here, I think it's incompatible with the new ubuntu 24.04.01

**Comment by jiwaszki** [comment]
@jpruiz114 @MonsterITServices @EDLLT I also encountered this issue. What helps me after the "default" installation is setting `export PYTHONPATH=/usr/local/lib/python3.12/site-packages/`. There is a small note in the guide about this tho (I missed it as well :smiling_face_with_tear: ).

However, there are couple of issues I have encountered on Ubuntu 24. It tends to hangs for "no specific reason", and it also is not able to broadcast the video on my two screens at the same time. I guess there is a little bit of debugging needed.

Second thing, if the package itself is nearly pure Python... why don't make it a wheel? It could be way easier to install.
Third thing is that  I was expecting it to be installed in my active virutualenv -- as it's not, PYTHONPATH has to be set manually.
