### ISSUE TITLE
the compiled build doesn't launch

### ISSUE THREAD

**Issue by DaRandomCube** [Komorebi-Fork/komorebi#95]
archlinux with kde plasma 6 on wayland
i heard that komorebi 3.0 supports wayland, so i went to compile and install
launched it from the command line -> no messages and not working
same but from the app menu -> same as above
any help?

**Comment by DaRandomCube** [comment]
tried launching again and it shows this
`ModuleNotFoundError: No module named 'komorebi'`

**Comment by Beast-Viper** [comment]
`Traceback (most recent call last):
  File "/usr/local/bin/komorebi", line 31, in <module>
    from komorebi.screen import Screen
ModuleNotFoundError: No module named 'komorebi'
`

Same here.

**Comment by dracid** [comment]
Same here.
xx@xx-framework:~$ komorebi
Traceback (most recent call last):
  File "/usr/local/bin/komorebi", line 31, in <module>
    from komorebi.screen import Screen
ModuleNotFoundError: No module named 'komorebi'

**Comment by Beast-Viper** [comment]
Maybe someone should fork this and fix it.

I am no developer and don't know any programming language (except 1% of C++).

**Comment by Styre-x** [comment]
I know this is mostly a dead project. But in case someone wants to use it;
this can be fixed by adding to $PYTHONPATH:
```
export PYTHONPATH=/usr/local/lib/python3/dist-packages/:$PYTHONPATH
```
Where /usr/local ... is where the install is located. It differs on distros, I'm personally on Mint, but you can find this when running meson install, it will look something like this:
```
Compiling '/usr/local/lib/python3/dist-packages/komorebi/screen.py'...
```
